name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"

kv_namespaces = [
  { binding = "NOTES", id = "849f02ef1a3244e08927a8dd6a19c97e" },
  { binding = "SHARE", id = "b53bcfb409df4c4b84abdeaf8cc849c6" }
]