name: Deploy cloud-notepad

on:
  workflow_dispatch:  # 手动触发
  push:
    branches:
      - master  # 推送到 master 分支时自动部署

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Workers

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Generate password hash
        id: gen_hash
        run: |
          HASH=$(node -e "
          const crypto = require('crypto');
          const password = '${{ secrets.SCN_APP_PASSWORD }}';
          const salt = '${{ secrets.SCN_SALT }}';

          if (password) {
            const hash1 = crypto.createHash('md5').update(password).digest('hex');
            const hash2 = crypto.createHash('md5').update(hash1 + '+' + salt).digest('hex');
            console.log(hash2);
          } else {
            console.log('');
          }
          ")
          echo "APP_PASSWORD_HASH=$HASH" >> $GITHUB_OUTPUT

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: "3.78.12"
          secrets: |
            APP_PASSWORD
        env:
          APP_PASSWORD: ${{ steps.gen_hash.outputs.APP_PASSWORD_HASH }}
